{
  "result":"我是远程js带来的数据",
  "purl":[{"url":"../html2p/pg1.jpg"},
          {"url":"../html2p/pg2.jpg"},
          {"url":"../html2p/pg3.jpg"},
          {"url":"../html2p/pg4.jpg"},
          {"url":"../html2p/pg5.jpg"},
          {"url":"../html2p/pg6.jpg"},
          {"url":"../html2p/pg7.jpg"},
          {"url":"../html2p/pg8.jpg"},
          {"url":"../html2p/pg9.jpg"},
          {"url":"../html2p/pg10.jpg"},
          {"url":"../html2p/pg11.jpg"},
          {"url":"../html2p/pg12.jpg"},
          {"url":"../html2p/pg13.jpg"},
          {"url":"../html2p/pg14.jpg"},
          {"url":"../html2p/pg15.jpg"}
  ]
}